SYNCQT.HEADER_FILES = egl.h eglext.h eglext_angle.h eglplatform.h 
SYNCQT.GENERATED_HEADER_FILES = 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
