SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtkmssupportversion.h QtKmsSupportVersion QtKmsSupport 
SYNCQT.PRIVATE_HEADER_FILES = qkmsdevice_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
