SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtmultimediagsttoolsversion.h QtMultimediaGstToolsVersion QtMultimediaGstTools 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
