SYNCQT.HEADER_FILES = quiloader.h 
SYNCQT.GENERATED_HEADER_FILES = QUiLoader qtuitoolsversion.h QtUiToolsVersion QtUiTools 
SYNCQT.PRIVATE_HEADER_FILES = quiloader_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = quiloader.h 
SYNCQT.INJECTIONS = 
