SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qt3dcoretestversion.h Qt3DCoreTestVersion Qt3DCoreTest 
SYNCQT.PRIVATE_HEADER_FILES = qbackendnodetester_p.h testpostmanarbiter_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
