SYNCQT.HEADER_FILES = qtpurchasingglobal.h inapppurchase/qinappproduct.h inapppurchase/qinappstore.h inapppurchase/qinapptransaction.h 
SYNCQT.GENERATED_HEADER_FILES = QInAppProduct QInAppStore QInAppTransaction qtpurchasingversion.h QtPurchasingVersion QtPurchasing 
SYNCQT.PRIVATE_HEADER_FILES = inapppurchase/qinapppurchasebackend_p.h inapppurchase/qinapppurchasebackendfactory_p.h inapppurchase/qinappstore_p.h inapppurchase/android/qandroidinappproduct_p.h inapppurchase/android/qandroidinapppurchasebackend_p.h inapppurchase/android/qandroidinapptransaction_p.h inapppurchase/mac/qmacinapppurchasebackend_p.h inapppurchase/mac/qmacinapppurchaseproduct_p.h inapppurchase/mac/qmacinapppurchasetransaction_p.h inapppurchase/winrt/qwinrtinappproduct_p.h inapppurchase/winrt/qwinrtinapppurchasebackend_p.h inapppurchase/winrt/qwinrtinapptransaction_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = qtpurchasingglobal.h inapppurchase/qinappproduct.h inapppurchase/qinappstore.h inapppurchase/qinapptransaction.h 
SYNCQT.INJECTIONS = 
