#! /bin/sh

set -e

. ${srcdir}/common

# Check quoted variables are stripped. In 0.28 and earlier, this would
# contain the "" quotes.
RESULT='/local/include'
run_test --variable=includedir variables

# Non-quoted variables are output as is. In 0.29, the \ would be stripped.
RESULT='-I"/local/include"/foo  -DFOO=\"/bar\"'
run_test --variable=cppflags variables

# Check the entire cflags output
RESULT='-DFOO=\"/bar\" -I/local/include -I/local/include/foo'
run_test --cflags variables
