#! /bin/sh

set -e

. ${srcdir}/common

# Check that debug output works with minimal output. This is still much
# more than desirable.

RESULT="PKG_CONFIG_DEBUG_SPEW variable enabling debug spew
Adding directory '$srcdir' from PKG_CONFIG_PATH
Global variable definition 'pc_sysrootdir' = '/'
Global variable definition 'pc_top_builddir' = '\$(top_builddir)'
Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
Error printing enabled
$PACKAGE_VERSION"
PKG_CONFIG_DEBUG_SPEW=1 run_test --version

RESULT="Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
Error printing enabled
$PACKAGE_VERSION"
run_test --debug --version
