#! /bin/sh

set -e

. ${srcdir}/common

RESULT="-I/non-l/include -I/non-l-required/include"
run_test --cflags non-l-required non-l
run_test --cflags --static non-l-required non-l

RESULT="/non-l.a /non-l-required.a -pthread"
run_test --libs non-l-required non-l
run_test --libs --static non-l-required non-l
