SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtedidsupportversion.h QtEdidSupportVersion QtEdidSupport 
SYNCQT.PRIVATE_HEADER_FILES = qedidparser_p.h qedidvendortable_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
