SYNCQT.HEADER_FILES = ../3rdparty/zlib/src/zconf.h ../3rdparty/zlib/src/zlib.h 
SYNCQT.GENERATED_HEADER_FILES = 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
