SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtdesignercomponentsversion.h QtDesignerComponentsVersion QtDesignerComponents 
SYNCQT.PRIVATE_HEADER_FILES = lib_pch.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
