SYNCQT.HEADER_FILES = qtconcurrent_global.h qtconcurrentcompilertest.h qtconcurrentexception.h qtconcurrentfilter.h qtconcurrentfilterkernel.h qtconcurrentfunctionwrappers.h qtconcurrentiteratekernel.h qtconcurrentmap.h qtconcurrentmapkernel.h qtconcurrentmedian.h qtconcurrentreducekernel.h qtconcurrentrun.h qtconcurrentrunbase.h qtconcurrentstoredfunctioncall.h qtconcurrentthreadengine.h 
SYNCQT.GENERATED_HEADER_FILES = QtConcurrentFilter QtConcurrentMap QtConcurrentRun qtconcurrentversion.h QtConcurrentVersion QtConcurrent 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = qtconcurrent_global.h qtconcurrentcompilertest.h qtconcurrentexception.h:concurrent qtconcurrentfilter.h qtconcurrentfilterkernel.h qtconcurrentfunctionwrappers.h qtconcurrentiteratekernel.h qtconcurrentmap.h qtconcurrentmapkernel.h qtconcurrentmedian.h qtconcurrentreducekernel.h qtconcurrentrun.h qtconcurrentrunbase.h qtconcurrentstoredfunctioncall.h qtconcurrentthreadengine.h 
SYNCQT.INJECTIONS = 
