#! /bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin

mount -a
/sbin/mdev -s
mount -a

echo "---------------------------------------------"
echo " Welcome debugging on Qemu Quard Star board! "
echo "---------------------------------------------"