/* This file was generated by syncqt. */
#ifndef QT_QTGAMEPAD_VERSION_H
#define QT_QTGAMEPAD_VERSION_H

#define QTGAMEPAD_VERSION_STR "5.12.11"

#define QTGAMEPAD_VERSION 0x050C0B

#endif // QT_QTGAMEPAD_VERSION_H
