SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtglxsupportversion.h QtGlxSupportVersion QtGlxSupport 
SYNCQT.PRIVATE_HEADER_FILES = qglxconvenience_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
