/* This file was generated by syncqt. */
#ifndef QT_QT3DINPUT_VERSION_H
#define QT_QT3DINPUT_VERSION_H

#define QT3DINPUT_VERSION_STR "5.12.11"

#define QT3DINPUT_VERSION 0x050C0B

#endif // QT_QT3DINPUT_VERSION_H
