SYNCQT.HEADER_FILES = 
SYNCQT.GENERATED_HEADER_FILES = qtgraphicssupportversion.h QtGraphicsSupportVersion QtGraphicsSupport 
SYNCQT.PRIVATE_HEADER_FILES = qrasterbackingstore_p.h 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
