SYNCQT.HEADER_FILES = qtx11extrasglobal.h qx11info_x11.h 
SYNCQT.GENERATED_HEADER_FILES = QX11Info qtx11extrasversion.h QtX11ExtrasVersion QtX11Extras 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = qtx11extrasglobal.h qx11info_x11.h 
SYNCQT.INJECTIONS = 
